export const SAVE_CAR_HATCHBACK_1 = 'SAVE_CAR_HATCHBACK_1'
export const SAVE_CAR_HATCHBACK_2 = 'SAVE_CAR_HATCHBACK_2'
export const SAVE_CAR_SUV_1 = 'SAVE_CAR_SUV_1'
export const SAVE_CAR_SUV_2 = 'SAVE_CAR_SUV_2'
