export const JsonData = [
    {
        CateogryName: 'Audio',
        CateogryImage: 'audio.jpg',
        ProductName: 'HeadPhone1',
        ProductImage: 'audio1.jpg',
        Cost: '$138',
    },
    {
        CateogryName: 'Audio',
        CateogryImage: 'audio.jpg',
        ProductName: 'HeadPhone2',
        ProductImage: 'audio2.jpg',
        Cost: '$100',
    },
    {
        CateogryName: 'Audio',
        CateogryImage: 'audio.jpg',
        ProductName: 'HeadPhone3',
        ProductImage: 'audio3.jpg',
        Cost: '$150',
    },
    {
        CateogryName: 'Audio',
        CateogryImage: 'audio.jpg',
        ProductName: 'HeadPhone4',
        ProductImage: 'audio4.jpg',
        Cost: '$70',
    },
    {
        CateogryName: 'Audio',
        CateogryImage: 'audio.jpg',
        ProductName: 'HeadPhone5',
        ProductImage: 'audio5.jpg',
        Cost: '$108',
    },
    {
        CateogryName: 'Chargers',
        CateogryImage: 'charger.jpg',
        ProductName: 'Charger1',
        ProductImage: 'charger1.jpg',
        Cost: '$18',
    },
    {
        CateogryName: 'Chargers',
        CateogryImage: 'charger.jpg',
        ProductName: 'Chargers2',
        ProductImage: 'charger2.jpg',
        Cost: '$25',
    },
    {
        CateogryName: 'Chargers',
        CateogryImage: 'charger.jpg',
        ProductName: 'Chargers3',
        ProductImage: 'charger3.jpg',
        Cost: '$40',
    },
    {
        CateogryName: 'Chargers',
        CateogryImage: 'charger.jpg',
        ProductName: 'Chargers4',
        ProductImage: 'charger4.jpg',
        Cost: '$100',
    },
    {
        CateogryName: 'Chargers',
        CateogryImage: 'charger.jpg',
        ProductName: 'Chargers5',
        ProductImage: 'charger5.jpg',
        Cost: '$50',
    },
    {
        CateogryName: 'PowerBanks',
        CateogryImage: 'powerbank.jpg',
        ProductName: 'PowerBanks1',
        ProductImage: 'powerbank1.jpg',
        Cost: '$50',
    },
    {
        CateogryName: 'PowerBanks',
        CateogryImage: 'powerbank.jpg',
        ProductName: 'PowerBanks2',
        ProductImage: 'powerbank2.jpg',
        Cost: '$100',
    },
    {
        CateogryName: 'PowerBanks',
        CateogryImage: 'powerbank.jpg',
        ProductName: 'PowerBanks3',
        ProductImage: 'powerbank3.jpg',
        Cost: '$23',
    },
    {
        CateogryName: 'PowerBanks',
        CateogryImage: 'powerbank.jpg',
        ProductName: 'PowerBanks4',
        ProductImage: 'powerbank4.jpg',
        Cost: '$23',
    },
    {
        CateogryName: 'PowerBanks',
        CateogryImage: 'powerbank.jpg',
        ProductName: 'PowerBanks5',
        ProductImage: 'powerbank5.jpg',
        Cost: '$23',
    },
    {
        CateogryName: 'Photography',
        CateogryImage: 'photography.jpg',
        ProductName: 'Photography1',
        ProductImage: 'photography1.jpg',
        Cost: '$200',
    },
    {
        CateogryName: 'Photography',
        CateogryImage: 'photography.jpg',
        ProductName: 'Photography2',
        ProductImage: 'photography2.jpg',
        Cost: '$230',
    },
    {
        CateogryName: 'Photography',
        CateogryImage: 'photography.jpg',
        ProductName: 'Photography3',
        ProductImage: 'photography3.jpg',
        Cost: '$250',
    },
    {
        CateogryName: 'Photography',
        CateogryImage: 'photography.jpg',
        ProductName: 'Photography4',
        ProductImage: 'photography4.jpg',
        Cost: '$250',
    },
    {
        CateogryName: 'Photography',
        CateogryImage: 'photography.jpg',
        ProductName: 'Photography5',
        ProductImage: 'photography5.jpg',
        Cost: '$300',
    },
]